
# Site settings
title: Lesley Luyang Song
name: Lesley Luyang Song
subtitle:  PhD Candidate
email: songly20@mails.tsinghua.edu.cn
description: >
   PhD Candidate in Marketing
baseurl: ""
url: "https://Lesley.com/"
github_username:  Lesley0909
disqus_baseurl: "https://Lesley.com/"
disqus_shortname: https-Lesley-com
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Lesley Luyang Song"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: Lesley0909
    url: https://github.com/Lesley0909
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: 宋璐阳
    url: https://www.linkedin.cn/incareer/in/ACoAACPZrgQBco6eJROSpuTLFV509g5R-TV9xnk
    desc: Connect with me on LinkedIn
    share: true
